name: ci
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    uses: genesys-ui/gh-workflows/.github/workflows/build.yml@main
  test:
    uses: genesys-ui/gh-workflows/.github/workflows/test.yml@main
    needs: [build]
  deploy:
    uses: genesys-ui/gh-workflows/.github/workflows/deploy.yml@main
    needs: [test]
