name: release
on:
  workflow_dispatch:
    inputs:
      dry:
        type: boolean
        description: Dry-mode (simulate publish)?
        default: true
        required: true
      version:
        type: choice
        description: Select version to release
        options:
          - major
          - minor
          - patch
          - auto
        default: auto
        required: true

run-name: release ${{ github.event.inputs.version }}${{ github.event.inputs.dry == 'true' && ' (--dry-run)' || '' }}

jobs:
  build:
    uses: genesys-ui/gh-workflows/.github/workflows/build.yml@main
  test:
    uses: genesys-ui/gh-workflows/.github/workflows/test.yml@main
    needs: [build]
  release:
    uses: genesys-ui/gh-workflows/.github/workflows/release.yml@main
    needs: [test]
    with:
      version: ${{ github.event.inputs.version }}
      dry: ${{ github.event.inputs.dry == 'true' }}
    secrets: inherit
